name: "ecostruxure"

chats:
    default: xxxxxxxxxxxxxxxxxx
    custom: xxxxxxxxxxxxxxxxxxx

Self-Test_in_Progress_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Self-Test_in_Progress_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Compensating for a high input voltage._Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Compensating for a high input voltage._Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Device_Communication_Alert_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Device_Communication_Alert_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Low_Battery_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Low_Battery_Cleared_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Input_Voltage_Or_Frequency_Cannot_Support_Bypass:
    web: true
    sql: false
    syslog: false
    teams: true
Input_Voltage_Or_Frequency_Cannot_Support_Bypass_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Input_Voltage_Or_Frequency_Cannot_Support_Bypass_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Input_Voltage_Or_Frequency_Can_Now_Support_Bypass:
    web: true
    sql: false
    syslog: false
    teams: true
Input_Voltage_Or_Frequency_Can_Now_Support_Bypass_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Input_Voltage_Or_Frequency_Can_Now_Support_Bypass_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Self-Test_in_Progress_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Self-Test_in_Progress_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Power_Failure_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Power_Failure_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true
Power_Failure_Cleared_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Undervoltage_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Undervoltage_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true
Undervoltage_Cleared_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

ALARM_ACTIVATION_LABEL_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
ALARM_CLEARED_LABEL_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

default:
    web: true
    sql: false
    syslog: false
    teams: true
