name: "EcoStruxure"

chats:
    user: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    default: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

Input_Voltage_Or_Frequency_Cannot_Support_Bypass_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Input_Voltage_Or_Frequency_Cannot_Support_Bypass_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Self-Test_in_Progress_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Self-Test_in_Progress_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

Power_Failure_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Power_Failure Cleared_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true
    
Undervoltage_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
Undervoltage_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

ALARM_ACTIVATION_LABEL_Activated:
    web: true
    sql: false
    syslog: false
    teams: true
ALARM_CLEARED_LABEL_Cleared:
    web: true
    sql: false
    syslog: false
    teams: true

default:
    web: true
    sql: false
    syslog: false
    teams: true
